### PR TITLE
security/osv-scanner: Update to 1.7.4

### PR DESCRIPTION
**Pull request by khorben**
Changes:
https://github.com/google/osv-scanner/compare/v1.7.1...v1.7.4

Sponsored by:	The FreeBSD Foundation

### CODE REVIEW

**Comment by khorben** [comment]
@lcook could you review this?

**Review by lcook — CHANGES_REQUESTED** [review]
Changes largely look fine, thank you! Would you mind updating  `_BUILD_COMMIT` to reflect the commit sha of the release?

**Comment by khorben** [comment]
> Changes largely look fine, thank you! Would you mind updating `_BUILD_COMMIT` to reflect the commit sha of the release?

Sure; I believe `d4657bf` is the correct hash. (https://github.com/google/osv-scanner/commit/d4657bf46aea52834c5148b25fb6cab132c69af5)

**Comment by khorben** [comment]
Superseded by #277.

**Pull request closed without merging**
