### PR TITLE
UBoot slave file for Odroid XU3 and NanoPi NEO2

### PR DESCRIPTION
**Pull request by nekoprog**

### CODE REVIEW

**Comment by evadot** [comment]
Hi,

I've just commited the nanopi-neo2 u-boot (https://svnweb.freebsd.org/ports?view=revision&revision=500658) which was submitted by phabricator.
I don't see a point of commiting the Odroid Xu3 since we don't run (or barely run on this board).
Thanks.

**Comment by nekoprog** [comment]
If we have odroid support, it would be great, but no problem. Can we have nanopi-r1 too?

**Comment by evadot** [comment]
Please submit a review on review.freebsd.org for that and assign it to me.
Thanks

**Comment by nekoprog** [comment]
@evadot Can you add for Odroid XU4? I uses same defconfig and u-boot salve port as Odroid XU3, it boast great specs for 32bit arm device.

Product page: https://www.hardkernel.com/shop/odroid-xu4-special-price/

**Pull request closed without merging**
