### PR TITLE
[sysutils/alloy] Update to v1.2.1

### PR DESCRIPTION
**Pull request by zalegrala**

### CODE REVIEW

**Comment by arrowd** [comment]
This port fails for me in Poudriere:

```
===> Fetching github.com/grafana/alloy/syntax dependency
(cd /portdistfiles/go/sysutils_alloy/grafana-alloy-v1.2.1_GH0; [ -e syntax/go.mod ] || mkdir syntax/;  tar -xzf grafana-alloy-v1.2.1_GH0.tar.gz alloy-1.2.1/syntax/go.mod;  cp alloy-1.2.1/syntax/go.mod syntax/go.mod)
alloy-1.2.1/syntax/go.mod: Can't unlink already-existing object: Permission denied
```

The port also does pretty uncommon things by appending to `_USES_fetch`. Can you just use usual `pre-fetch`, `post-fetch`, `pre-extract`, `post-extract` targets to run these commands?

**Comment by zalegrala** [comment]
Hmm, I'm able to build here.
```
[00:04:24] [01] [00:00:00] Building sysutils/alloy | alloy-1.2.1
[00:24:40] [01] [00:20:16] Finished sysutils/alloy | alloy-1.2.1: Success
```

I can test using the post-fetch or pre-extract approach as you mention.  Perhaps this change could be a follow up PR?

**Comment by arrowd** [comment]
>  Perhaps this change could be a follow up PR?

No, please update this PR with `pre`/`post` changes and I will fix the rest.

**Comment by zalegrala** [comment]
I've updated the PR to include targets you mentioned.  Surprisingly it built and ran, but let me know if anything else needs addressing.

**Comment by arrowd** [comment]
This is the Makefile I ended up with up with:
```
PORTNAME=	alloy
PORTVERSION=	1.2.1
DISTVERSIONPREFIX=v
CATEGORIES=	sysutils

MAINTAINER=	zach.leslie@grafana.com
COMMENT=	OpenTelemetry Collector distribution with programmable pipelines
WWW=		https://github.com/grafana/alloy

LICENSE=	MIT

BUILD_DEPENDS=	git:devel/git

USES=		go:1.22,modules

USE_GITHUB=	yes
GH_ACCOUNT=	grafana
GH_PROJECT=	alloy

USE_RC_SUBR=	alloy

GO_MODULE=	github.com/${GH_ACCOUNT}/${GH_PROJECT}
GO_PKGNAME=	github.com/${GH_ACCOUNT}/${GH_PROJECT}
GO_TARGET=	github.com/${GH_ACCOUNT}/${GH_PROJECT}
GO_BUILDFLAGS=	-ldflags='-X github.com/grafana/alloy/internal/build.Version=v${PORTVERSION}'

post-fetch:
	@${ECHO_MSG} "===> Fetching ${GO_MODNAME}/syntax dependency";
	(cd ${DISTDIR}/${DIST_SUBDIR}; [ -e syntax/go.mod ] || (\
		${MKDIR} syntax/; \
		${TAR} -xzf ${DISTNAME}${EXTRACT_SUFX} ${PORTNAME}-${PORTVERSION}/syntax/go.mod; \
		${CP} ${PORTNAME}-${PORTVERSION}/syntax/go.mod syntax/go.mod))
	@${ECHO_MSG} "===> Fetching ${GO_MODNAME}/internal/etc/datadogreceiver dependency";
	(cd ${DISTDIR}/${DIST_SUBDIR}; [ -e internal/etc/datadogreceiver/go.mod ] || (\
		${MKDIR} internal/etc/datadogreceiver/; \
		${TAR} -xzf ${DISTNAME}${EXTRACT_SUFX} ${PORTNAME}-${PORTVERSION}/internal/etc/datadogreceiver/go.mod; \
		${CP} ${PORTNAME}-${PORTVERSION}/internal/etc/datadogreceiver/go.mod internal/etc/datadogreceiver/go.mod))

post-extract:
	${CP} -r ${WRKDIR}/${PORTNAME}-${PORTVERSION}/syntax ${GO_WRKSRC}/syntax;
	${MKDIR} ${GO_WRKSRC}/internal/etc
	${CP} -r ${WRKDIR}/${PORTNAME}-${PORTVERSION}/internal/etc/datadogreceiver ${GO_WRKSRC}/internal/etc/datadogreceiver;

do-install:
	${INSTALL_PROGRAM} ${WRKDIR}/bin/alloy ${STAGEDIR}${PREFIX}/bin/alloy
	${INSTALL_DATA} ${WRKSRC}/example-config.alloy ${STAGEDIR}${PREFIX}/etc/alloy.flow.sample
	${MKDIR} ${STAGEDIR}/var/alloy

.include <bsd.port.mk>
```
Let me know if you're OK with it and I will push it to `main`.

**Comment by zalegrala** [comment]
Looks reasonable to me.  Ship it. What were the changes?  Also bring in the service script change as well please.

**Comment by arrowd** [comment]
Pushed, thank you.

**Comment by zalegrala** [comment]
Thank you @arrowd.

**Pull request closed without merging**
