### PR TITLE
First attempt at running PowerShell under FreeBSD.

### PR DESCRIPTION
**Pull request by erwinlem**
This is obviously a work in progress, but i can run it and do a get-childitem. Most likely this is not the best way to do it but I want to get some feedback before I invest more time. Runs in combination with dotnet and not mono.

It needs Powershell to build Powershell, so I used the Linux version with Linux emulation. Tried to get that tar as an extra distfile but could not get that to work. Manual download worked fine.

First objective was to make it run, now we have to make it nice and tidy.

### CODE REVIEW

**Comment by yurivict** [comment]
Try shells/nushell - it might be a very comparable, if not superior to PowerShell option.

**Comment by arrowd** [comment]
It'd be great if you approach upstream with all these patches you came up with.

**Comment by Martinfx** [comment]
https://github.com/Martinfx/FreeBSD-Ports/tree/max-powershell/powershell

**Comment by erwinlem** [comment]
Also found this one via wanted ports : https://reviews.freebsd.org/D16707

@Martinfx : Nice! That seems like decent work. Wanted to remove the linux part later and use nuget as wel. Will your version be merged into ports? Then it makes more sense to use your version and close my attempt. Will test it tomorrow to see if it works.

@arrowd: Mostly just ripped out the login shell, but the question is what to do with that. To blindly execute sh to set the environment variables seems a bit weird. A ~/.powershellrc or something would make a lot more sense. Following the same course as linux/Mac would be best for now. Upstream wil be more interested in things like get-proces/get-service/new-localuser and that kind of stuff to work. I hope. Or having the sysctl mapped as a drive like the registry in windows would be interesting.

**Comment by Thefrank** [comment]
Upstream might be a heavy lift :) 
https://github.com/PowerShell/PowerShell-Native/pull/92 < - no clue on the hold
https://github.com/PowerShell/PowerShell/pull/20041 <- needs rebase it is so old AND had one blocking test failure (terminal corruption)
https://github.com/pester/Pester/pull/2385 <- test infra, already closed due to missing upstream code and 1yr wait

If anyone wants to pick up the effort, I can close mine out so there is no conflicts

https://people.freebsd.org/~zirias/patches/0001-shells-powershell-Add-new-port.patch <- work done by others

**Comment by Martinfx** [comment]
> Upstream might be a heavy lift :) [PowerShell/PowerShell-Native#92](https://github.com/PowerShell/PowerShell-Native/pull/92) < - no clue on the hold [PowerShell/PowerShell#20041](https://github.com/PowerShell/PowerShell/pull/20041) <- needs rebase it is so old AND had one blocking test failure (terminal corruption) [pester/Pester#2385](https://github.com/pester/Pester/pull/2385) <- test infra, already closed due to missing upstream code and 1yr wait
> 
> If anyone wants to pick up the effort, I can close mine out so there is no conflicts
> 
> https://people.freebsd.org/~zirias/patches/0001-shells-powershell-Add-new-port.patch <- work done by others

The path is broken `powershell/work/PowerShell-7.4.1/src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs(89,35): error CS0103: The name 'InitializeTypeCatalog' does not exist in the current context [powershell/work/PowerShell-7.4.1/src/System.Management.Automation/System.Management.Automation.csproj]
`

**Comment by Thefrank** [comment]
@Martinfx / @erwinlem I can close out my upstream PRs if desired. They have been stalled for over the year with no sign of success. It looks like it is time for others to try. Hopefully fresh PRs get traction... I also never got around to getting 100% test clearance with pwsh's own tests :(

**Comment by erwinlem** [comment]
> https://github.com/Martinfx/FreeBSD-Ports/tree/max-powershell/powershell

This one works, only the .net needed a patch (https://reviews.freebsd.org/D44561). I can test my powershell scripts and see what breaks.

I'm closing this pull request to avoid confusion. Feel free to take anything I made and I would recommend to put effort in the version or Martin.

**Pull request closed without merging**
