### PR TITLE
Add uwsgi_emperor support

### PR DESCRIPTION
**Pull request by Kronuz**
Emperor mode was not supported, this pull request adds support to it.
Use by setting uwsgi_emperor="/directory/to/uwsgi/vassals"

### CODE REVIEW

**Comment by mat813** [comment]
Openned a PR https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210170

**Comment by Dafvid** [comment]
Still not committed =/

**Comment by Dafvid** [comment]
Trying to make this work but I have issues.
- rc is spawning two processes and I can't seem to kill both. why 2?
- is there a better way than rm -f to stop the process ('uwsgi stop <pid>')?
- how about just open up for passing a path to config and set everything up in there instead?

**Comment by rakuco** [comment]
It'd be great if you could post comments to Bugzilla instead. The port maintainer is not watching this pull request (which was closed last year) and any further discussions here are likely to get ignored by the relevant parties. FWIW I'm also CC'ed in Bugzilla and can help you land this once the issues are solved.

**Pull request closed without merging**
