### PR TITLE
multimedia/emby-server(-devel): pass -P to daemon(8)

### PR DESCRIPTION
**Pull request by jcassette**
With the -r option, the -P option must be used instead of the -p option. Otherwise, when stopping the service, daemon will restart the child. See man daemon(8).

### CODE REVIEW

**Comment by driesmp** [comment]
I'll take this

**Comment by driesmp** [comment]
I don't think switch -p to -P is enough, when querying status of the daemon with eg service emby-server status, it is not detected running when it is. The same for stopping the daemon. Have you given your patch a shot?

I think both are needed with -r probably something like here can be adopted, creating a pid dir, where both the pid of the child and the daemon are located.

https://cgit.freebsd.org/ports/tree/net-p2p/radarr/files/radarr.in

**Comment by driesmp** [comment]
So weird, I can't get it to work on my setup with -P or even with -P and -p.

**Comment by ConstrictM** [comment]
The short answer if you need both a daemon pidfile and pidfile.

Also the services need to be killed as they do not shutdown gracefully.

**Comment by driesmp** [comment]
Oh found it, do you have an e-mail address jcassette?

**Comment by driesmp** [comment]
> You can also push to my branch since "Allow edits by maintainers" is enabled
Doesn't matter, as we cant commit from GH, its read only.

**Comment by driesmp** [comment]
Should be fixed!

**Pull request closed without merging**
