### PR TITLE
Update multimedia/py-soco to 0.29.1

### PR DESCRIPTION
**Pull request by conallob**
Upstream release on 2023-02-18

Release notes: https://github.com/SoCo/SoCo/releases/tag/v0.29.1

### CODE REVIEW

**Comment by conallob** [comment]
See also https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269698

**Comment by metalefty** [comment]
testbuild in progress

**Comment by metalefty** [comment]
Committed, thanks! BTW, you only need to raise either pull request or bugzilla bug.

**Comment by conallob** [comment]
I only opened bugzilla bug in parallel, since I find both bugs and pull requests can have long review latency.


Thanks for reviewing!

**Pull request closed without merging**
