### PR TITLE
comms/hackrf: port update 2021.03.1->2024.02.1.

### PR DESCRIPTION
**Pull request by cederom**
Release 2024.02.1 notes:
https://github.com/greatscottgadgets/hackrf/releases/tag/v2024.02.1

### CODE REVIEW

**Comment by opsec** [comment]
Build fails on 14.0, 15.0 with:

```
CMake` Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FFTW (missing: FFTW_INCLUDES)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindFFTW.cmake:28 (find_package_handle_standard_args)
  hackrf-tools/src/CMakeLists.txt:26 (find_package)
```

**Comment by opsec** [comment]
LIB_DEPENDS needs libfftw3.so:math/fftw3

**Comment by opsec** [comment]
Committed as [bbde357477](https://cgit.FreeBSD.org/ports/commit/?id=bbde357477e249e2df05d25e2f36564094eec6b0)

**Comment by cederom** [comment]
> LIB_DEPENDS needs libfftw3.so:math/fftw3

Hmm, `make staging-qa` told me it is not needed so I have removed that depend.. should I bring it back? :-)

**Comment by cederom** [comment]
TANK U @opsec :-)

**Pull request closed without merging**
