### PR TITLE
Update librewolf to 131.0.3

### PR DESCRIPTION
**Pull request by tempcracks**

### CODE REVIEW

**Comment by Martinfx** [comment]
Did you test in poudriere ?

**Comment by tempcracks** [comment]
Yes, tested on 14.1-RELEASE. Sorry for not pointing out earlier

@Martinfx

**Comment by Martinfx** [comment]
> Yes, tested on 14.1-RELEASE. Sorry for not pointing out earlier
> 
> @Martinfx

thank you but Bugzilla bug is close https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282423 . You can close this bug.

**Comment by tempcracks** [comment]
Thank you for finding time
@Martinfx

**Pull request closed without merging**
