### PR TITLE
www/falkon: update package description

### PR DESCRIPTION
**Pull request by grahamperrin**
It's no longer 'new-ish'.

Whilst here, rewrite things slightly.

### CODE REVIEW

**Comment by grahamperrin** [comment]
Background: [#37 - FreeBSD Handbook: consistency, modernisation: www/falkon - freebsd-doc - Codeberg.org](https://codeberg.org/grahamperrin/freebsd-doc/pulls/37)

**Comment by grahamperrin** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274547

**Comment by BSDKaffee** [comment]
We generally avoid using double spaces after a full stop. The use of a single space is standard in modern writing. "Edition" is a noun. I would replace it with the verb "editing". The word "Manager" in "SSL Manager" should be lowercase since it used generically. Bulleted lists that don't complete the sentence stem should not be punctuated. I would also remove the hyphen before "qtonly" because that is the name of the flavor.

**Comment by grahamperrin** [comment]
Thank you, 

> The word "Manager" in "SSL Manager" should be lowercase since it used generically. 

Should the same be done for the _CA certificates database_? There's currently an uppercase C for Certificates.

**Comment by grahamperrin** [comment]
> We generally avoid using double spaces after a full stop. The use of a single space is standard in modern writing. 

Agreed, generally; with exceptions in some FreeBSD Project contexts – and the exceptions are not yet suitably documented. My https://github.com/freebsd/freebsd-src/commit/edacf4b4824af3630a953eb1080baf9c46f176de (removal of a double space) was treated as an error, and so on. 

Briefly: can you think of any context where representation of a package description, making _direct_ use of e.g. the `pkg-descr` file for a port, is **not** monospaced?

**Comment by BSDKaffee** [comment]
> Should the same be done for the _CA certificates database_? There's currently an uppercase C for Certificates.

Yes, it is a generic term. I'd make it singular too. "CA certificate database" sounds better.

**Comment by BSDKaffee** [comment]
> Briefly: can you think of any context where representation of a package description, making _direct_ use of e.g. the `pkg-descr` file for a port, is **not** monospaced?

Probably any port maintained by danfe@. He's a fellow grammar pedant, which I appreciate, but I disagree about double spaces after full stops. It's not wrong, just a dated writing style. It used to write that way myself, to be honest, but have kicked the habit.

**Comment by BSDKaffee** [comment]
> My [freebsd/freebsd-src@edacf4b](https://github.com/freebsd/freebsd-src/commit/edacf4b4824af3630a953eb1080baf9c46f176de) (removal of a double space) was treated as an error, and so on.

I don't know why removing a double space from UPDATING would cause an error. There is a great lack of consistency with regards to double space vs. monospace after a full stop in that file, even within some of the individual entries.

**Comment by arrowd** [comment]
Merged, thanks.

**Pull request closed without merging**
