### PR TITLE
Fix git clone and working on repo under Windows

### PR DESCRIPTION
**Pull request by PhilZ-cwm6**
Windows can support long file names, but these file names are not allowed:
CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8,
COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9

Source: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

### CODE REVIEW

**Comment by PhilZ-cwm6** [comment]
This should allow cloning or working on the repo remotely from a Windows machine

**Comment by yurivict** [comment]
If an OS can't support a file name ```prn``` - this is obviously a bug there. It doesn't make sense to rename all such files everywhere, rather the bug should be fixed.

Did you try to report this to Microsoft?

**Comment by rene0** [comment]
You will also need to add a line to MOVED, somehting like
`japanese/prn|japanese/prn-bin|2022-03-20|Allow cloning the repository on Windows`

**Comment by PhilZ-cwm6** [comment]
@yurivict : this is not a freebsd vs ms, every os has its restrictions. Win restrictions are all in the official doc I linked to. There is no way to work on the repo using Github Desktop or any win system without respecting os limitations

@rene0 : feel free to amend my commit, or specify exactly where I would add this line ?

Best regards

**Comment by PhilZ-cwm6** [comment]
Added the commit to MOVED, but did not rebase and there is conflict with MOVED
I think that compatibility to work on the repo from windows should be preserved

**Comment by PhilZ-cwm6** [comment]
squashed and rebased on current branch

**Comment by michael-o** [comment]
Rename the port to `pr0n`.

**Comment by clausecker** [comment]
@PhilZ-cwm6 The restrictions on file names on POSIX systems is that they must be nonempty and may not contain NUL bytes or the slash character.  Any other file name is permitted.  I don't think compatibility with Windows is of importance to the FreeBSD project in this regard.

**Comment by 0mp** [comment]
Committed with minor changes via [f3050fcad38de7820c9ec5d54b86da9bda689131](https://github.com/freebsd/freebsd-ports/commit/f3050fcad38de7820c9ec5d54b86da9bda689131). Thanks for the patch.

**Pull request closed without merging**
