### PR TITLE
net/openbgpd7: update 7.6 -> 7.7, and check_process fix

### PR DESCRIPTION
**Pull request by guggemand**
- Upgrade from 7.6 to 7.7
- Fix check_process, "bgpd: parent" no longer matches anything
- Remove unused IPV6LLPEER option

### CODE REVIEW

**Comment by jbeich** [comment]
Requires review/approval by @opsec (maintainer). Looks like this hasn't been submitted via bugzilla, so cannot land under "maintainer timeout".

**Comment by opsec** [comment]
This says: The base branch restricts merging to authorized users. I approve the update. But how to proceed ?

**Comment by jbeich** [comment]
@opsec, download commits (manually or [via Git](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally)), maybe rebase to adjust commit messages to FreeBSD style and/or add a keyword to [auto-close by commit](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) then land as usual (and close the PR if not auto-closed).

Try playing against [development repo](https://cgit-dev.freebsd.org/ports/) first. If still unsure ask on [git@ list](https://lists.freebsd.org/subscription/freebsd-git) as someone may have written a guide.

Examples:
```
$ fetch -qo- https://github.com/freebsd/freebsd-ports/pull/141.patch | git am
$ git push --push-option=confirm-author freebsd
```
```
$ git fetch https://github.com/freebsd/freebsd-ports pull/141/head
$ git rebase -i origin FETCH_HEAD
$ git push --push-option=confirm-author freebsd @:main
```

**Comment by jbeich** [comment]
Oops, it's already documented in https://docs.freebsd.org/en/articles/committers-guide/#github-pull-land

**Comment by opsec** [comment]
Thanks , [committed](https://cgit.FreeBSD.org/ports/commit/?id=e2bb42ebb0765df9dd1b86d7eb145de993f6a418)

**Pull request closed without merging**
