### PR TITLE
CentOS 7 Aarch64 support

### PR DESCRIPTION
**Pull request by darkain**
~~WARNING: SOME OF THESE CHANGE BREAK I386/AMD64~~

Just making a PR because it also generates a simple diff URL to pass around for anyone else interested in this body of work.

TODO:
- ~~Check each individual port to see if they have architecture specific pkg-plist files, and generate a new file for Aarch64~~
  - MOSTLY done with this item, just 7 stubborn ports remaining.
- ~~linux-c7-dri is all kinds of broken and has sections of i386/amd64 upstream packages commented out, rather than properly architecture gated~~
- At least one port had issues with DISTFILES, but I don't remember which or what that issue was off the top of my head. This issue only effected "makesum" though, so I temporarily disabled DISTFILES while making the checksums on one of these, and then re-enabled it afterwards.
- Regression testing on i386 and AMD64 to ensure none of these changes break the existing architectures.

Remaining ports to fix:

- ~~devel/linux-c7-strace~~
- devel/linux-c7-sdl20
- audio/linux-c7-alsa-plugins-oss
- audio/linux-c7-libsndfile
- audio/linux-c7-pulseaudio-libs
- audio/linux-c7-flac
- audio/linux-c7-alsa-plugins-pulseaudio

More details can be found over at the FreeBSD Bugzilla: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256008

### CODE REVIEW

**Comment by xmj** [comment]
Hi, this is awesome. How do I help?  Best, Johannes

**Comment by darkain** [comment]
> Hi, this is awesome. How do I help? Best, Johannes

Sharing here as well as on Twitter in case someone sees either.

> I'm tracking the work log on Bugzilla, and list things that are blockers there at any given time.
> Currently only 7 ports left to fix, and then its regression testing all of them on amd64, i386, aarch64
> https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256008

**Comment by heroku-miraheze** [comment]
Github PRs are not allowed. Please do not merge.

**Comment by bsdimp** [comment]
> Github PRs are not allowed. Please do not merge.

That's not true, and hasn't been true since the FreeBSD project moved to git.

Also, it's a shitty reason to reject otherwise good code. Large, complex changes like this are actually better as a pull request rather than some other vector because they are more likely to land w/o introduced mistakes.

**Comment by arrowd** [comment]
This PR seems to be merged. Should it be closed?

**Comment by darkain** [comment]
> This PR seems to be merged. Should it be closed?

Agreed, looks like Aarch64 Linux C7 packages are being built now. Closing this PR.

https://www.freshports.org/emulators/linux_base-c7/

**Pull request closed without merging**
