### PR TITLE
Update the DeforaOS Desktop packages to the latest versions available

### PR DESCRIPTION
**Pull request by khorben**
This updates a number of packages relevant to the DeforaOS Desktop environment, and imports one as well:
* Editor 0.4.1
* Integration 0.1.3
* Keyboard 0.4.0
* libDesktop 0.4.2
* Mailer 0.2.0
* Notes 0.2.1 (new import)
* Panel 0.4.6
* Player 0.2.0
* Todo 0.3.1

Changes suggested by `portclippy(1)`, `portfmt(1)`, and `portlint(1)` have been applied on every package.

Tested on FreeBSD/amd64 with Xorg.

Additional fixes for Wayland support are still pending changes upstream, together with the corresponding releases.

### CODE REVIEW

**Comment by khorben** [comment]
Cc @Jehops, @ocochard; thanks!

**Comment by ocochard** [comment]
ok for portlint, but did you test them with a `poudriere testport` ?


```
poudriere testport -j builder -p deforaos mail/deforaos-mailer
(etc.)
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/doc/Mailer/COPYING
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
```

About editors/deforaos-editor: 
```
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/man/html1/editor.html.gz
Error: Orphaned: share/man/html1/filter.html.gz
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
```

**Comment by Jehops** [comment]
@khorben, these ports also have plist issues:
- editors/deforaos-editor
- deskutils/deforaos-notes
- deskutils/deforaos-todo

**Comment by khorben** [comment]
> ok for portlint, but did you test them with a `poudriere testport` ? [...]

No, but thanks for the heads up!

I can set it up on my side, unless one of you beats me to it 😁

**Comment by khorben** [comment]
> > ok for portlint, but did you test them with a `poudriere testport` ? [...]
> 
> No, but thanks for the heads up!
> 
> I can set it up on my side, unless one of you beats me to it 😁

I have setup an instance of poudriere, and found and fixed some issues already. I haven't tested everything completely yet.

**Comment by khorben** [comment]
> I have setup an instance of poudriere, and found and fixed some issues already. I haven't tested everything completely yet.

I have fixed a couple more issues in `editors/deforaos-editor` and `mail/deforaos-mailer`.

**Comment by Jehops** [comment]
For the two remaining plist errors, you need to add `share/doc/Todo/COPYING` to `deskutils/deforaos-todo/pkg-plist` and `share/doc/Notes/COPYING` to `deskutils/deforaos-notes/pkg-plist`.

**Comment by khorben** [comment]
Thanks, I have done that, and added an `NLS` option to `www/deforaos-surfer` as well.

**Comment by khorben** [comment]
I have fixed another issue, where a dependency was missing for `mail/deforaos-mailer`, namely on `textproc/gtk-doc` for the `DOCS` option.

**Comment by khorben** [comment]
I believe the pull-request is now ready; did you find any other issue to fix?

**Comment by ocochard** [comment]
Done: Thanks a lot.

**Pull request closed without merging**
