### PR TITLE
Update blocky.in

### PR DESCRIPTION
**Pull request by smileymattj**
enable logging file in rc.d daemon for the blocky service.

### CODE REVIEW

**Comment by diizzyy** [comment]
Hi, 
Please submit this via https://bugs.freebsd.org as this is a read only repo

Best regards,
Daniel

**Comment by smileymattj** [comment]
Thanks for pointing me in the right direction diizzyy.  Sorry for submitting it in the wrong place.

**Comment by rosorio** [comment]
PR created on bugzilla
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276499

**Comment by rosorio** [comment]
Committed, thanks
 https://cgit.freebsd.org/ports/commit/?id=5d038a444a3187093fe185fc0f1ebd06596a6cf5

**Pull request closed without merging**
