### PR TITLE
Temp fix for zmq4 and ipv6

### PR DESCRIPTION
**Pull request by melvyn-sopacua**
Ref: https://github.com/zeromq/zeromq4-1/issues/43

Trigger: @koobs

### CODE REVIEW

**Comment by lwhsu** [comment]
@koobs: how do you think of this?

**Comment by koobs** [comment]
@lwhsu Approved to commit. Please add the header from https://github.com/zeromq/zeromq4-1/commit/81464652d2453c608bbbb52fd59e9e9f20857178.patch to the top of the files/ patch

Thanks @melvyn-sopacua !

**Comment by koobs** [comment]
@lwhsu This also needs to be MFH'd to 2015Q3

@melvyn-sopacua If this issue applies to previous branches of zeromq for which we have ports, please feel free to submit patches them them too

**Comment by lwhsu** [comment]
This is committed as https://svnweb.freebsd.org/changeset/ports/393665

**Comment by koobs** [comment]
Thank you @lwhsu

**Pull request closed without merging**
