### PR TITLE
sysutils/py-mqttwarn: Update documentation

### PR DESCRIPTION
**Pull request by amotl**
Dear @dlangille,

following up on your recent commit 53fec2142f28f6, and my proposal at https://github.com/jpmens/mqttwarn/issues/646#issuecomment-1528730347, I am submitting this patch in order to slightly update the documentation for `sysutils/py-mqttwarn`. Other than this, it fixes a minor typo on a variable within the package Makefile. Let me know about any adjustments you would like to see.

With kind regards,
Andreas.

### CODE REVIEW

**Comment by dlangille** [comment]
There is no direct merging from here into the FreeBSD ports tree.

I can patch my local tree and use `--author="Andreas Motl <your-email>" if you like.  If so, please le me know what email address to use there. I can also not use `--author` if you like.

Also, I can wait until I have more time to figure out the path for doing this as a `--cherry-pick`

**Comment by amotl** [comment]
Hi Dan,

if you want to try that procedure, this would be the way to do it with two `--cherry-pick`s.
```
git remote add temp https://github.com/freebsd/freebsd-ports
git fetch temp
git cherry-pick 36479f3772da87bf8450cf2731195bb05f25b81a
git cherry-pick c6ef6b858d55068fc775bcde32399f8c3ad560e8
git remote remove temp
```

Otherwise, you can also use my author tag `Andreas Motl <andreas.motl@panodata.org>`.

Thank you in advance!

With kind regards,
Andreas.

**Comment by dlangille** [comment]
I tried. I failed. 

```
[22:09 pkg01 dan ~/src/ports/sysutils/py-mqttwarn] % git cherry-pick 36479f3772da87bf8450cf2731195bb05f25b81a
fatal: bad object 36479f3772da87bf8450cf2731195bb05f25b81a
```

I tried again. Failed same why. So I downloaded the patch and tried another way.

For now, we have this:

```
commit 35c70b0431781b47c33d8b977e020e18b5480558 (HEAD -> main)
Author: Andreas Motl <andreas.motl@panodata.org>
Date:   Thu May 4 22:19:01 2023 +0000

    sysutils/py-mqttwarn: Rename option REISPUB to REDISPUB
    
    The REISPUB option was spelled wrong. Let's rename it.
    
    While here, add an UPDATING entry to let the users know it changed.
```

**Comment by amotl** [comment]
Thanks. 36479f3772da87bf8450cf2731195bb05f25b81a would be the more important one. I don't know why cherry-picking fails. You can download it at [^1].

[^1]: https://github.com/freebsd/freebsd-ports/commit/36479f3772da87bf8450cf2731195bb05f25b81a.patch

**Comment by amotl** [comment]
It looks like the updates made it to https://www.freshports.org/sysutils/py-mqttwarn/ already, on behalf of 35c70b0431781b47c33d8b977e020e18b5480558 and de3dea784e9376c9b1b36dae194ac59fe1a5bf03. Thank you so much, and sorry for the broken WWW line. Closing this.

**Pull request closed without merging**
